<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBgPKOzV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBgPKOzV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBgPKOzV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBgPKOzV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBgPKOzV\App_KernelDevDebugContainer([
    'container.build_hash' => 'BgPKOzV',
    'container.build_id' => 'be9fcd01',
    'container.build_time' => 1586881544,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBgPKOzV');
