<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLC92YOe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLC92YOe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLC92YOe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLC92YOe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLC92YOe\App_KernelDevDebugContainer([
    'container.build_hash' => 'LC92YOe',
    'container.build_id' => 'ee804985',
    'container.build_time' => 1583578222,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLC92YOe');
