<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'homepage' => [[], ['_controller' => 'App\\Controller\\HomePageController::index'], [], [['text', '/']], [], []],
    'accueil' => [[], ['_controller' => 'App\\Controller\\HomePageController::accueil'], [], [['text', '/Accueil']], [], []],
    'AjouterReservation' => [[], ['_controller' => 'App\\Controller\\ReservationController::ajout'], [], [['text', '/AjouterReservation']], [], []],
    'Reservations' => [[], ['_controller' => 'App\\Controller\\ReservationController::index'], [], [['text', '/Reservations']], [], []],
    'Admin_Reservations' => [[], ['_controller' => 'App\\Controller\\ReservationController::index_admin'], [], [['text', '/Admin/Reservations']], [], []],
    'Admin_Liste_Reservations' => [['id'], ['_controller' => 'App\\Controller\\ReservationController::afficher_reservations'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Admin/Reservations']], [], []],
    'Admin_Gerer_Reservations' => [['id'], ['_controller' => 'App\\Controller\\ReservationController::gerer_reservation'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Admin/Reservations/Gerer']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/app_login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'informations' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/Informations']], [], []],
    'show_user' => [['id'], ['_controller' => 'App\\Controller\\UserController::show_user'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Admin/Informations']], [], []],
    'enregistrement' => [[], ['_controller' => 'App\\Controller\\UserController::register'], [], [['text', '/Enregistrement']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\HomePageController::index'], [], [['text', '/']], [], []],
];
